### ISSUE TITLE
회원가입-API 개발

### ISSUE THREAD

**Issue by jungmini0601** [jungmini0601/csnote-server#1]
**TO-DO**
- [x] 회원 도메인 계층 개발
- [x] 회원 엔티티 개발
- [x] 회원 서비스 개발
- [x] 회원 가입 유즈케이스 개발
- [x] 인증 서비스 개발
- [x] 비밀번호 암호화 기능 개발 (Security)
- [x] 회원 컨트롤러 개발
- [x] 스웨거 붙이기

**TO-BE**
- [ ] 1일차 기술 문서 작성 - (기술 의사 결정, 고려한 점, 문제점)
- [x] 테스트 코드 작성
- [x] 스크래치 파일 작성
