### ISSUE TITLE
문제 상세 조회 기능 추가

### ISSUE THREAD

**Issue by jungmini0601** [jungmini0601/csnote-server#23]
**TODO**

- [x] 컨트롤러 계층 개발
- [x] 유즈케이스 계층 개발
- [x] 저장소 계층 개발
- [x] 저장소 계층 단위 테스트
- [x] 유즈케이스 계층 단위 테스트
- [x] 컨트롤러 계층 단위 테스트

**구현시 신경 써야 하는 점**
- 로컬 캐싱 적용 전 / 후 응답시간 비교
- 전: 60 ~ 100 ms 전후
- 후: 1ms ~ 40 ms
