### ISSUE TITLE
로그인 기능 리팩토링

### ISSUE THREAD

**Issue by jungmini0601** [jungmini0601/csnote-server#9]
**TODO**
- [x] 로그인 API 컨트롤러를 제거한다.
- [x] 필터 기반 인증 시스템으로 변경한다.
- [x] 리프레시 토큰은 레디스 프리티어를 쓰기로 했으므로 관련 코드 추가가 필요하다.
- [x] 변경된 설계로 인해 필요가 없어진 코드는 삭제 또는 Deprecated 시켜 놓는다.
